/**
 * Demo providers for development only.
 * Never used as production data.
 */

import type { ProviderProfile } from '@/types';

export function buildDemoProviders(): ProviderProfile[] {
  const now = new Date().toISOString();
  const base = {
    role: 'provider' as const,
    email: 'demo@example.com',
    emailVerified: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
    notificationPreferences: {
      email: true,
      push: true,
      sms: false,
      marketing: false,
      jobAlerts: true,
      messages: true,
      bookingUpdates: true,
      paymentNotifications: true,
    },
    businessType: 'sole_trader' as const,
    status: 'verified' as const,
    verificationStatus: 'approved' as const,
    insuranceVerified: true,
    qualifications: [] as string[],
    certifications: [] as string[],
    portfolioImageIds: [] as string[],
    subServiceIds: [] as string[],
    pricing: {
      currency: 'GBP' as const,
      pricingModel: 'mixed' as const,
      callOutFee: 60,
      hourlyRate: 55,
    },
    workingHours: { timezone: 'Europe/London' },
    onboardingStep: 12,
    onboardingCompleted: true,
    phoneVerified: true,
  };

  return [
    {
      ...base,
      id: 'prov-1',
      displayName: 'John Mitchell',
      businessName: "John's Heating & Plumbing",
      description: 'Emergency boiler repairs, central heating, radiators and plumbing.',
      availabilityStatus: 'available_now',
      yearsExperience: 14,
      rating: 4.9,
      reviewCount: 187,
      completedJobs: 214,
      responseRate: 0.96,
      averageResponseTimeSeconds: 45,
      acceptanceRate: 0.88,
      cancellationRate: 0.02,
      serviceIds: ['plumbing', 'heating'],
      emergencyAvailable: true,
      serviceAreas: [
        {
          id: 'sa-1',
          providerId: 'prov-1',
          radiusMiles: 20,
          center: { latitude: 53.4808, longitude: -2.2426 },
          active: true,
        },
      ],
      maxTravelMiles: 25,
    },
    {
      ...base,
      id: 'prov-2',
      displayName: 'Sarah Khan',
      businessName: 'QuickFix Plumbing Manchester',
      description: 'Burst pipes, leaks, blocked drains and emergency call-outs.',
      availabilityStatus: 'available_now',
      yearsExperience: 8,
      rating: 4.7,
      reviewCount: 92,
      completedJobs: 156,
      responseRate: 0.91,
      averageResponseTimeSeconds: 70,
      acceptanceRate: 0.82,
      cancellationRate: 0.04,
      serviceIds: ['plumbing', 'drainage'],
      emergencyAvailable: true,
      serviceAreas: [
        {
          id: 'sa-2',
          providerId: 'prov-2',
          radiusMiles: 15,
          center: { latitude: 53.47, longitude: -2.23 },
          active: true,
        },
      ],
    },
    {
      ...base,
      id: 'prov-3',
      displayName: 'Mike Okafor',
      businessName: 'Okafor Electrical Services',
      description: 'Emergency electrician, sockets, lighting and fuse boards.',
      availabilityStatus: 'available_later',
      yearsExperience: 11,
      rating: 4.8,
      reviewCount: 134,
      completedJobs: 198,
      responseRate: 0.89,
      averageResponseTimeSeconds: 120,
      acceptanceRate: 0.85,
      cancellationRate: 0.03,
      serviceIds: ['electrical'],
      emergencyAvailable: true,
      serviceAreas: [
        {
          id: 'sa-3',
          providerId: 'prov-3',
          radiusMiles: 18,
          center: { latitude: 53.46, longitude: -2.25 },
          active: true,
        },
      ],
    },
    {
      ...base,
      id: 'prov-4',
      displayName: 'Emma Davies',
      businessName: 'SecureLock Locksmiths',
      description: '24/7 emergency locksmith, lock changes and lost keys.',
      availabilityStatus: 'available_now',
      yearsExperience: 6,
      rating: 4.6,
      reviewCount: 67,
      completedJobs: 89,
      responseRate: 0.94,
      averageResponseTimeSeconds: 35,
      acceptanceRate: 0.9,
      cancellationRate: 0.01,
      serviceIds: ['locksmith'],
      emergencyAvailable: true,
      serviceAreas: [
        {
          id: 'sa-4',
          providerId: 'prov-4',
          radiusMiles: 12,
          center: { latitude: 53.475, longitude: -2.24 },
          active: true,
        },
      ],
    },
    {
      ...base,
      id: 'prov-5',
      displayName: 'Tom Bradley',
      businessName: 'Bradley Boilers Ltd',
      description: 'Gas Safe registered. Boiler repair, installation and servicing.',
      availabilityStatus: 'busy',
      yearsExperience: 18,
      rating: 4.95,
      reviewCount: 312,
      completedJobs: 450,
      responseRate: 0.98,
      averageResponseTimeSeconds: 40,
      acceptanceRate: 0.75,
      cancellationRate: 0.01,
      serviceIds: ['heating', 'plumbing'],
      emergencyAvailable: true,
      serviceAreas: [
        {
          id: 'sa-5',
          providerId: 'prov-5',
          radiusMiles: 25,
          center: { latitude: 53.49, longitude: -2.26 },
          active: true,
        },
      ],
    },
  ];
}
