/**
 * Initial UK service taxonomy seed data.
 * In production this lives in Firestore and is managed by admins.
 */

export const SERVICE_CATEGORIES = [
  {
    id: 'plumbing',
    slug: 'plumbing',
    name: 'Plumbing',
    description: 'Emergency plumbing, leaks, boilers, drains and more',
    isEmergencyEligible: true,
    sortOrder: 1,
    keywords: ['plumber', 'plumbing', 'pipe', 'leak', 'drain', 'tap', 'toilet', 'sink'],
    synonyms: ['pipes', 'leaking', 'blocked', 'burst'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'electrical',
    slug: 'electrical',
    name: 'Electrical',
    description: 'Electricians for repairs, rewiring, sockets and safety',
    isEmergencyEligible: true,
    sortOrder: 2,
    keywords: ['electrician', 'electrical', 'socket', 'fuse', 'wiring', 'lights'],
    synonyms: ['power', 'electrics', 'circuit'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'heating',
    slug: 'heating',
    name: 'Heating',
    description: 'Boiler repair, central heating, radiators',
    isEmergencyEligible: true,
    sortOrder: 3,
    keywords: ['boiler', 'heating', 'radiator', 'central heating', 'thermostat'],
    synonyms: ['no heat', 'cold radiator', 'boiler broken'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'locksmith',
    slug: 'locksmith',
    name: 'Locksmith',
    description: 'Emergency lockouts, lock changes and repairs',
    isEmergencyEligible: true,
    sortOrder: 4,
    keywords: ['locksmith', 'lock', 'keys', 'door', 'lockout'],
    synonyms: ['locked out', 'lost keys', 'broken lock'],
    defaultRadiusMiles: 12,
  },
  {
    id: 'cleaning',
    slug: 'cleaning',
    name: 'Cleaning',
    description: 'Domestic and commercial cleaning services',
    isEmergencyEligible: false,
    sortOrder: 5,
    keywords: ['cleaner', 'cleaning', 'house clean', 'deep clean'],
    synonyms: ['housework', 'domestic cleaning'],
    defaultRadiusMiles: 10,
  },
  {
    id: 'gardening',
    slug: 'gardening',
    name: 'Gardening',
    description: 'Garden maintenance, landscaping and clearance',
    isEmergencyEligible: false,
    sortOrder: 6,
    keywords: ['gardener', 'gardening', 'lawn', 'hedge', 'garden'],
    synonyms: ['lawn mowing', 'weeding', 'landscaping'],
    defaultRadiusMiles: 12,
  },
  {
    id: 'pest-control',
    slug: 'pest-control',
    name: 'Pest Control',
    description: 'Removal of pests, insects and rodents',
    isEmergencyEligible: true,
    sortOrder: 7,
    keywords: ['pest', 'mice', 'rats', 'wasps', 'insects', 'infestation'],
    synonyms: ['rodents', 'bugs', 'pest control'],
    defaultRadiusMiles: 20,
  },
  {
    id: 'appliance-repair',
    slug: 'appliance-repair',
    name: 'Appliance Repair',
    description: 'Washing machines, dishwashers, fridges and more',
    isEmergencyEligible: false,
    sortOrder: 8,
    keywords: ['appliance', 'washing machine', 'dishwasher', 'fridge', 'oven'],
    synonyms: ['broken appliance', 'white goods'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'roofing',
    slug: 'roofing',
    name: 'Roofing',
    description: 'Roof repairs, leaks and replacements',
    isEmergencyEligible: true,
    sortOrder: 9,
    keywords: ['roof', 'roofer', 'roofing', 'tiles', 'gutter'],
    synonyms: ['roof leak', 'missing tiles'],
    defaultRadiusMiles: 20,
  },
  {
    id: 'building',
    slug: 'building',
    name: 'Building',
    description: 'General building, extensions and renovations',
    isEmergencyEligible: false,
    sortOrder: 10,
    keywords: ['builder', 'building', 'extension', 'renovation'],
    synonyms: ['construction', 'building work'],
    defaultRadiusMiles: 25,
  },
  {
    id: 'handyman',
    slug: 'handyman',
    name: 'Handyman',
    description: 'General repairs and odd jobs around the home',
    isEmergencyEligible: false,
    sortOrder: 11,
    keywords: ['handyman', 'odd jobs', 'repairs', 'fixing'],
    synonyms: ['general repairs', 'odd job'],
    defaultRadiusMiles: 12,
  },
  {
    id: 'painting-decorating',
    slug: 'painting-decorating',
    name: 'Painting & Decorating',
    description: 'Interior and exterior painting and decorating',
    isEmergencyEligible: false,
    sortOrder: 12,
    keywords: ['painter', 'decorator', 'painting', 'decorating'],
    synonyms: ['paint', 'wallpaper'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'carpentry',
    slug: 'carpentry',
    name: 'Carpentry',
    description: 'Joinery, doors, kitchens and custom woodwork',
    isEmergencyEligible: false,
    sortOrder: 13,
    keywords: ['carpenter', 'carpentry', 'joiner', 'doors', 'cupboards'],
    synonyms: ['woodwork', 'joinery'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'flooring',
    slug: 'flooring',
    name: 'Flooring',
    description: 'Laminate, hardwood, carpet and tile flooring',
    isEmergencyEligible: false,
    sortOrder: 14,
    keywords: ['flooring', 'carpet', 'laminate', 'tiles', 'floor'],
    synonyms: ['floor fitting'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'drainage',
    slug: 'drainage',
    name: 'Drainage',
    description: 'Blocked drains, CCTV surveys and drain repairs',
    isEmergencyEligible: true,
    sortOrder: 15,
    keywords: ['drain', 'drainage', 'blocked drain', 'sewer'],
    synonyms: ['drain unblock', 'flooded drain'],
    defaultRadiusMiles: 20,
  },
  {
    id: 'glazing',
    slug: 'glazing',
    name: 'Glazing',
    description: 'Windows, glass repairs and double glazing',
    isEmergencyEligible: true,
    sortOrder: 16,
    keywords: ['glazier', 'glazing', 'window', 'glass', 'double glazing'],
    synonyms: ['broken window', 'glass repair'],
    defaultRadiusMiles: 15,
  },
  {
    id: 'moving',
    slug: 'moving',
    name: 'Moving',
    description: 'House removals and man-with-van services',
    isEmergencyEligible: false,
    sortOrder: 17,
    keywords: ['removal', 'moving', 'man and van', 'house move'],
    synonyms: ['removals', 'van hire'],
    defaultRadiusMiles: 30,
  },
  {
    id: 'bathroom-kitchen',
    slug: 'bathroom-kitchen',
    name: 'Bathroom & Kitchen',
    description: 'Bathroom and kitchen fitting and refurbishment',
    isEmergencyEligible: false,
    sortOrder: 18,
    keywords: ['bathroom', 'kitchen', 'fitting', 'refurbishment'],
    synonyms: ['bathroom fit', 'kitchen fit'],
    defaultRadiusMiles: 20,
  },
] as const;

export const SAMPLE_KEYWORDS = [
  // Plumbing emergency
  { term: 'burst pipe', aliases: ['pipe burst', 'broken pipe', 'pipe leaking'], serviceId: 'plumbing', weight: 3 },
  { term: 'water leak', aliases: ['leaking water', 'water leaking', 'leak'], serviceId: 'plumbing', weight: 2.5 },
  { term: 'blocked sink', aliases: ['sink blocked', 'blocked basin'], serviceId: 'plumbing', weight: 2 },
  { term: 'toilet blocked', aliases: ['blocked toilet', 'toilet not flushing'], serviceId: 'plumbing', weight: 2 },
  { term: 'emergency plumber', aliases: ['urgent plumber', 'plumber now'], serviceId: 'plumbing', weight: 3 },
  // Heating
  { term: 'boiler broken', aliases: ['boiler not working', 'boiler failed', 'no heating'], serviceId: 'heating', weight: 3 },
  { term: 'radiator cold', aliases: ['cold radiator', 'radiator not heating'], serviceId: 'heating', weight: 2.5 },
  { term: 'no hot water', aliases: ['hot water gone', 'no heating or hot water'], serviceId: 'heating', weight: 2.5 },
  // Electrical
  { term: 'power cut', aliases: ['no power', 'electrics gone', 'fuse box'], serviceId: 'electrical', weight: 2.5 },
  { term: 'socket not working', aliases: ['dead socket', 'socket broken'], serviceId: 'electrical', weight: 2 },
  // Locksmith
  { term: 'locked out', aliases: ['lock out', 'keys locked inside', 'cant get in'], serviceId: 'locksmith', weight: 3 },
  { term: 'lost keys', aliases: ['keys lost', 'no keys'], serviceId: 'locksmith', weight: 2.5 },
  // General
  { term: 'emergency', aliases: ['urgent', 'asap', 'right now', 'immediately'], serviceId: 'plumbing', weight: 1.5 },
];
